from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .config import PROFILE_TOOLS
from .scaffold_safety import repository_relative_path


_SHA = re.compile(r"[0-9a-fA-F]{40}\Z")
_VARIABLE = re.compile(r"[A-Z][A-Z0-9_]{0,63}\Z")
_LABEL = re.compile(r"[A-Za-z0-9][A-Za-z0-9_.-]{0,63}\Z")


def build_github_workflow(
    *,
    target: Path,
    output: Path,
    profile: str,
    config_path: str,
    checkout_sha: str,
    upload_artifact_sha: str,
    upload_sarif_sha: str,
    policy_variable: str,
    isolation_command: str,
    runner_labels: tuple[str, ...],
) -> tuple[str, dict[str, Any]]:
    """Build a pinned, no-install GitHub workflow and non-authoritative receipt."""
    if profile not in PROFILE_TOOLS:
        raise ValueError(f"unsupported profile: {profile}")
    pins = {
        "actions/checkout": _validated_sha(checkout_sha, "checkout SHA"),
        "actions/upload-artifact": _validated_sha(
            upload_artifact_sha, "upload-artifact SHA"
        ),
        "github/codeql-action/upload-sarif": _validated_sha(
            upload_sarif_sha, "upload-sarif SHA"
        ),
    }
    if _VARIABLE.fullmatch(policy_variable) is None:
        raise ValueError("policy variable must be an uppercase GitHub variable name")
    labels = runner_labels or ("self-hosted", "pysec-isolated")
    if len(labels) > 8 or any(_LABEL.fullmatch(label) is None for label in labels):
        raise ValueError("runner labels must be 1-8 bounded GitHub label values")
    isolation = isolation_command.strip()
    if (
        not isolation
        or len(isolation) > 500
        or any(character in isolation for character in ("\r", "\n", "\x00"))
    ):
        raise ValueError("isolation command must be one non-empty bounded line")
    config = repository_relative_path(config_path, "configuration")
    rendered = _workflow_yaml(
        profile=profile,
        config=config,
        pins=pins,
        policy_variable=policy_variable,
        isolation_command=isolation,
        labels=labels,
    )
    receipt = {
        "schema_version": "1.0",
        "schema_id": "urn:project-py-security-suite:schema:github-workflow:1.0",
        "authoritative": False,
        "status": "generated",
        "target": target.name,
        "output": output.relative_to(target).as_posix(),
        "profile": profile,
        "configuration": config,
        "runner_labels": list(labels),
        "action_pins": pins,
        "safety_controls": [
            "pre-provisioned enterprise runner",
            "explicit external isolation verification",
            "immutable 40-character action commit pins",
            "least-privilege workflow permissions",
            "credential persistence disabled",
            "scan exit preserved until artifacts are uploaded",
            "report verification before admission",
        ],
        "scope": (
            "Workflow scaffold only. It installs nothing and does not create the "
            "network boundary, approve scanner identities, or authorize release."
        ),
    }
    return rendered, receipt


def render_workflow_receipt(receipt: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"GENERATED: {receipt['output']}",
            f"Profile: {receipt['profile']}",
            f"Runner: {', '.join(receipt['runner_labels'])}",
            f"Pinned actions: {len(receipt['action_pins'])}",
            f"Scope: {receipt['scope']}",
        ]
    )


def _validated_sha(value: str, label: str) -> str:
    if _SHA.fullmatch(value) is None:
        raise ValueError(f"{label} must be exactly 40 hexadecimal characters")
    return value.casefold()


def _workflow_yaml(
    *,
    profile: str,
    config: str,
    pins: dict[str, str],
    policy_variable: str,
    isolation_command: str,
    labels: tuple[str, ...],
) -> str:
    runner = ", ".join(labels)
    return f"""# Generated by pysec generate-ci. Review under change control.
name: Python security

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: [{runner}]
    env:
      PYSEC_ORGANIZATION_POLICY: ${{{{ vars.{policy_variable} }}}}
    steps:
      - name: Check out exact revision
        uses: actions/checkout@{pins["actions/checkout"]}
        with:
          persist-credentials: false

      - name: Verify externally enforced isolation
        shell: bash
        run: |
          {isolation_command}

      - name: Run isolated suite and retain decision
        id: pysec
        shell: bash
        run: |
          set +e
          python -m py_security_suite scan . \\
            --config {config} \\
            --policy "${{PYSEC_ORGANIZATION_POLICY:?set {policy_variable}}}" \\
            --profile {profile} \\
            --network-isolated \\
            --github-summary \\
            --output .artifacts/pysec-report
          result=$?
          echo "exit_code=$result" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Verify sealed report
        if: always()
        shell: bash
        run: |
          python -m py_security_suite verify-report \\
            .artifacts/pysec-report --format json \\
            --output .artifacts/pysec-report-verification.json

      - name: Upload report and verification receipt
        if: always()
        uses: actions/upload-artifact@{pins["actions/upload-artifact"]}
        with:
          name: python-security-report
          path: |
            .artifacts/pysec-report/
            .artifacts/pysec-report-verification.json
          if-no-files-found: error
          retention-days: 30

      - name: Publish SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@{pins["github/codeql-action/upload-sarif"]}
        with:
          sarif_file: .artifacts/pysec-report/results.sarif
          category: python-security-suite

      - name: Apply scan decision
        if: always()
        shell: bash
        run: test "${{{{ steps.pysec.outputs.exit_code }}}}" -eq 0
"""
