from __future__ import annotations

from pathlib import Path
from typing import Any

from .config import PROFILE_TOOLS
from .scaffold_safety import repository_relative_path


def build_precommit_config(
    *,
    target: Path,
    output: Path,
    profile: str,
    config_path: str,
) -> tuple[str, dict[str, Any]]:
    """Build local, activation-free pre-commit diagnostics and their receipt."""
    if profile not in PROFILE_TOOLS:
        raise ValueError(f"unsupported profile: {profile}")
    config = repository_relative_path(config_path, "configuration")
    rendered = _precommit_yaml(profile=profile, config=config)
    receipt = {
        "schema_version": "1.0",
        "schema_id": "urn:project-py-security-suite:schema:precommit-config:1.0",
        "authoritative": False,
        "status": "generated",
        "target": target.name,
        "output": output.relative_to(target).as_posix(),
        "profile": profile,
        "configuration": config,
        "hooks": [
            {
                "id": "pysec-adapter-contracts",
                "purpose": "Validate the installed adapter registry without running scanners.",
                "command": ["python", "-m", "py_security_suite", "adapter-check"],
            },
            {
                "id": "pysec-profile-readiness",
                "purpose": "Validate profile applicability, assets, trust, and prerequisites.",
                "command": [
                    "python",
                    "-m",
                    "py_security_suite",
                    "doctor",
                    ".",
                    "--config",
                    config,
                    "--profile",
                    profile,
                    "--explain",
                ],
            },
        ],
        "safety_controls": [
            "local repository entry only",
            "system interpreter; no dependency installation",
            "no filenames or source content forwarded by pre-commit",
            "non-executing adapter and readiness diagnostics only",
            "no network-isolation or release-approval claim",
        ],
        "scope": (
            "Developer diagnostics only. These hooks do not execute the scanner portfolio, "
            "establish an egress-denied boundary, or replace the production admission gate."
        ),
    }
    return rendered, receipt


def render_precommit_receipt(receipt: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"GENERATED: {receipt['output']}",
            f"Profile: {receipt['profile']}",
            f"Hooks: {len(receipt['hooks'])}",
            "Mode: local diagnostics; no scanner execution or installation",
            f"Scope: {receipt['scope']}",
        ]
    )


def _precommit_yaml(*, profile: str, config: str) -> str:
    return f"""# Generated by pysec generate-hooks. Review under change control.
minimum_pre_commit_version: '3.5.0'

repos:
  - repo: local
    hooks:
      - id: pysec-adapter-contracts
        name: Python Security Suite - adapter contracts
        entry: python -m py_security_suite adapter-check
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
        stages: [pre-commit]

      - id: pysec-profile-readiness
        name: Python Security Suite - {profile} readiness
        entry: >-
          python -m py_security_suite doctor . --config {config}
          --profile {profile} --explain
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
        stages: [pre-commit]
"""
