from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .config import PROFILE_TOOLS

PROJECT_TEMPLATES = (
    "api",
    "cli",
    "library",
    "monorepo",
    "worker",
)

_DEFAULT_PROFILES = {
    "api": "comprehensive",
    "cli": "repo",
    "library": "standard",
    "monorepo": "comprehensive",
    "worker": "comprehensive",
}

_TEMPLATE_GUIDANCE = {
    "api": (
        "# API roots are normally discovered from FastAPI, Flask, or Django decorators.\n"
        '# entry_points = ["app.main:app"]\n\n'
        "[tools.schemathesis]\n"
        'artifacts_path = ".artifacts/test-evidence/schemathesis-junit.xml"\n\n'
        "[tools.zap]\n"
        'artifacts_path = ".artifacts/test-evidence/zap.json"\n'
    ),
    "cli": (
        "# Console scripts are discovered from pyproject.toml. Add reflective or\n"
        "# plugin roots only when static discovery cannot see them.\n"
        '# entry_points = ["package.cli:main"]\n'
    ),
    "library": (
        "# Public package exports are treated conservatively as reachable. Add\n"
        "# framework or plugin entry points when consumers load them indirectly.\n"
        '# entry_points = ["package.public:Client"]\n'
    ),
    "monorepo": (
        "# Uncomment and tailor roots when automatic src/package discovery is not\n"
        "# sufficient for the repository layout.\n"
        '# source_roots = ["services/api/src", "packages/shared/src"]\n'
    ),
    "worker": (
        "# Celery tasks and common decorators are discovered automatically. Declare\n"
        "# scheduler, plugin, or dependency-injection roots that are loaded indirectly.\n"
        '# entry_points = ["package.worker:run"]\n'
    ),
}


def render_project_config(template: str, profile: str | None = None) -> str:
    """Render a minimal, valid, offline-first repository configuration."""
    if template not in PROJECT_TEMPLATES:
        raise ValueError(
            f"unknown project template {template!r}; choose one of: "
            + ", ".join(PROJECT_TEMPLATES)
        )
    selected_profile = project_profile(template, profile)
    return f'''# Generated by pysec init for a {template} project.
# Repository configuration selects controls but cannot grant organization approval.
schema_version = "1"
profile = "{selected_profile}"

[isolation]
network = "deny"
require_attestation = true
execute_target_code = false

[execution]
max_workers = 4
max_output_bytes = 16777216

[policy]
required_scanners = []
block_severities = ["critical", "high"]
incomplete_is_blocking = true

[reports]
include_sanitized_evidence = true

[intelligence]
require_approval = false
maximum_age_days = 3
epss_high_probability = 0.10
epss_high_percentile = 0.90

[tools.reachability]
enabled = true
executable = "pysec"
minimum_island_loc = 100
discover_framework_roots = true
{_TEMPLATE_GUIDANCE[template]}
'''.rstrip()


def project_profile(template: str, profile: str | None = None) -> str:
    """Resolve the explicit or template-recommended profile."""
    if template not in PROJECT_TEMPLATES:
        raise ValueError(
            f"unknown project template {template!r}; choose one of: "
            + ", ".join(PROJECT_TEMPLATES)
        )
    selected_profile = profile or _DEFAULT_PROFILES[template]
    if selected_profile not in PROFILE_TOOLS:
        raise ValueError(f"unknown scan profile: {selected_profile}")
    return selected_profile


def build_init_receipt(
    *, target: Path, config_path: Path, template: str, profile: str
) -> dict[str, Any]:
    """Describe an initialized repository without leaking its absolute location."""
    relative = config_path.relative_to(target).as_posix()
    selected = PROFILE_TOOLS[profile]
    return {
        "schema_version": "1.0",
        "schema_id": "urn:project-py-security-suite:schema:project-init:1.0",
        "status": "initialized",
        "authoritative": False,
        "target": target.name,
        "template": template,
        "profile": profile,
        "configuration": relative,
        "selected_tools": len(selected),
        "next_steps": [
            {
                "order": 1,
                "purpose": "Inspect prerequisites without executing scanners.",
                "argv": [
                    "pysec",
                    "doctor",
                    ".",
                    "--config",
                    relative,
                    "--profile",
                    profile,
                    "--explain",
                ],
                "authority": "repository",
            },
            {
                "order": 2,
                "purpose": "Run the configured portfolio inside an externally enforced isolated boundary.",
                "argv": [
                    "pysec",
                    "scan",
                    ".",
                    "--config",
                    relative,
                    "--profile",
                    profile,
                    "--network-isolated",
                    "--output",
                    ".artifacts/pysec-report",
                ],
                "authority": "external-isolation",
            },
        ],
        "scope": (
            "Repository bootstrap only; scanner acquisition, external isolation, "
            "trust approval, signing, and release admission remain separate."
        ),
    }


def render_init_receipt(receipt: dict[str, Any]) -> str:
    """Render concise operator guidance after project initialization."""
    lines = [
        f"INITIALIZED: {receipt['configuration']} ({receipt['template']}, {receipt['profile']})",
        f"Selected controls: {receipt['selected_tools']}",
        "Next steps:",
    ]
    lines.extend(
        (
            f"{step['order']}. {step['purpose']}\n   argv: "
            + json.dumps(step["argv"], ensure_ascii=False)
        )
        for step in receipt["next_steps"]
    )
    lines.append(f"Scope: {receipt['scope']}")
    return "\n".join(lines)
