"""Render the risk-route overview separately from detailed tables."""

from typing import Any


def render_risk_path_intro(summary: Any) -> list[str]:
    lines = [
        "",
        "## Static risk routes",
        "",
        "These bounded Graphify routes retain every matched declared Python entry point to review targets and their owner/test evidence. A route is triage context, not proof of attacker control, exploitability, or sensitive-data flow.",
        "",
        "| Signal | Count |",
        "|---|---:|",
        f"| Declared entry points | {int(summary.get('entry_points', 0))} |",
        f"| Finding targets | {int(summary.get('finding_targets', 0))} |",
        f"| Sensitive sink-surface targets | {int(summary.get('sink_surface_targets', 0))} |",
        f"| Dependency-advisory importer targets | {int(summary.get('dependency_advisory_import_targets', 0))} |",
        f"| Routed dependency-advisory importers | {int(summary.get('routed_dependency_advisory_imports', 0))} |",
        f"| Retained declared-entry exposures | {int(summary.get('retained_entry_point_exposures', 0))} |",
        f"| Entry exposures runtime observed / unobserved / unavailable | {int(summary.get('observed_entry_point_exposures', 0))} / {int(summary.get('unobserved_entry_point_exposures', 0))} / {int(summary.get('entry_point_exposures_without_runtime_evidence', 0))} |",
        f"| Routes reached by multiple entry points | {int(summary.get('routes_with_multiple_entry_points', 0))} |",
        f"| Multi-entry routes with unobserved interfaces | {int(summary.get('multi_entry_routes_with_unobserved_interfaces', 0))} |",
        f"| Multi-entry routes with interface runtime-evidence gaps | {int(summary.get('multi_entry_routes_with_runtime_evidence_gaps', 0))} |",
        f"| Security routes reached by multiple entry points | {int(summary.get('security_routes_with_multiple_entry_points', 0))} |",
        f"| Maximum entry points for one route | {int(summary.get('maximum_entry_points_per_route', 0))} |",
        f"| Routes with entry-point exposure truncation | {int(summary.get('routes_with_entry_point_exposure_truncation', 0))} |",
        f"| Routes with assured scanner evidence | {int(summary.get('assured_evidence_routes', 0))} |",
        f"| Single-perspective routes | {int(summary.get('single_perspective_routes', 0))} |",
        f"| Independently corroborated routes | {int(summary.get('independently_corroborated_routes', 0))} |",
        f"| Routes with scanner trust / execution gaps | {int(summary.get('routes_with_tool_trust_gaps', 0))} / {int(summary.get('routes_with_tool_execution_gaps', 0))} |",
        f"| Routes without direct tool assurance | {int(summary.get('routes_without_tool_assurance', 0))} |",
        f"| Finding routes with comparable lifecycle | {int(summary.get('routes_with_comparable_finding_lifecycle', 0))} |",
        f"| Finding routes without comparable lifecycle | {int(summary.get('routes_without_comparable_finding_lifecycle', 0))} |",
        f"| Baseline-new or regressed routes | {int(summary.get('baseline_new_or_regressed_routes', 0))} |",
        f"| Baseline-new or regressed routes on changed lines | {int(summary.get('baseline_new_or_regressed_changed_routes', 0))} |",
        f"| Baseline-new or regressed changed routes with validation gaps | {int(summary.get('baseline_new_or_regressed_changed_routes_with_validation_gaps', 0))} |",
        f"| Pre-existing finding routes on changed lines | {int(summary.get('existing_finding_routes_at_changed_lines', 0))} |",
        f"| Routes with ownership evidence | {int(summary.get('routes_with_ownership_evidence', 0))} |",
        f"| Routes crossing ownership boundaries | {int(summary.get('routes_crossing_ownership_boundaries', 0))} |",
        f"| Exact ownership handoffs | {int(summary.get('ownership_boundaries', 0))} |",
        f"| Routes with unowned segments | {int(summary.get('routes_with_unowned_segments', 0))} |",
        f"| Routes without ownership evidence | {int(summary.get('routes_without_ownership_evidence', 0))} |",
        f"| Distinct route owners | {int(summary.get('distinct_route_owners', 0))} |",
        f"| Unrouted dependency-advisory importers | {int(summary.get('unrouted_dependency_advisory_imports', 0))} |",
        f"| Distinct routed dependency advisories | {int(summary.get('distinct_routed_dependency_advisories', 0))} |",
        f"| Known-exploited / high-EPSS dependency routes | {int(summary.get('known_exploited_dependency_routes', 0))} / {int(summary.get('high_epss_dependency_routes', 0))} |",
        f"| Dependency routes with fixed versions | {int(summary.get('dependency_routes_with_fixed_versions', 0))} |",
        f"| Dependency routes with validation gaps | {int(summary.get('dependency_routes_with_validation_gaps', 0))} |",
        f"| Dependency routes at changed importers | {int(summary.get('dependency_routes_at_changed_importers', 0))} |",
        f"| Dependency routes with uncovered changed lines | {int(summary.get('dependency_routes_with_uncovered_changed_lines', 0))} |",
        f"| Dependency routes with comparable source/artifact inventory | {int(summary.get('dependency_routes_with_comparable_package_lifecycle', 0))} |",
        f"| Dependency routes with source/artifact version drift | {int(summary.get('dependency_routes_with_version_drift', 0))} |",
        f"| Dependency routes source-only / artifact-only | {int(summary.get('dependency_routes_source_only_in_comparable_inventory', 0))} / {int(summary.get('dependency_routes_artifact_only_in_comparable_inventory', 0))} |",
        f"| Dependency routes with composition evidence gaps | {int(summary.get('dependency_routes_with_composition_evidence_gaps', 0))} |",
        f"| Dependency routes with exact fixed version in artifact | {int(summary.get('dependency_routes_with_exact_fixed_version_in_artifact', 0))} |",
        f"| Exact-path exposure / advisory intersections | {int(summary.get('exposure_advisory_intersections', 0))} |",
        f"| Known-exploited exposure / advisory intersections | {int(summary.get('known_exploited_exposure_advisory_intersections', 0))} |",
        f"| Unprotected exposure / advisory intersections | {int(summary.get('unprotected_exposure_advisory_intersections', 0))} |",
        f"| Exposure / advisory intersections with validation gaps | {int(summary.get('exposure_advisory_intersections_with_validation_gaps', 0))} |",
        f"| End-to-end sensitive-data routes | {int(summary.get('sensitive_data_routes', 0))} |",
        f"| Scanner-confirmed / inventory-only sensitive-data routes | {int(summary.get('scanner_confirmed_sensitive_data_routes', 0))} / {int(summary.get('inventory_sensitive_data_routes', 0))} |",
        f"| Sensitive-data routes without observed protection | {int(summary.get('sensitive_data_routes_without_observed_protection', 0))} |",
        f"| Sensitive-data routes with runtime-observed entry points | {int(summary.get('sensitive_data_routes_with_runtime_observed_entry_points', 0))} |",
        f"| Sensitive-data routes with validation / scanner-assurance gaps | {int(summary.get('sensitive_data_routes_with_validation_gaps', 0))} / {int(summary.get('sensitive_data_routes_with_assurance_gaps', 0))} |",
        f"| Sensitive-data routes crossing ownership boundaries / reached by multiple entry points | {int(summary.get('sensitive_data_routes_crossing_ownership_boundaries', 0))} / {int(summary.get('sensitive_data_routes_with_multiple_entry_points', 0))} |",
        f"| Sensitive-data routes with / without applicable citations | {int(summary.get('sensitive_data_routes_with_citations', 0))} / {int(summary.get('sensitive_data_routes_without_citations', 0))} |",
        f"| Secret candidates assessed / total | {int(summary.get('secret_candidates_assessed', 0))} / {int(summary.get('secret_candidates', 0))} |",
        f"| Secret candidates in production / test / generated evidence | {int(summary.get('production_source_secret_candidates', 0))} / {int(summary.get('test_source_secret_candidates', 0))} / {int(summary.get('generated_evidence_secret_candidates', 0))} |",
        f"| Secret candidates in artifacts / repository controls | {int(summary.get('artifact_secret_candidates', 0))} / {int(summary.get('repository_control_secret_candidates', 0))} |",
        f"| Secret candidates with history / scanner verification | {int(summary.get('history_secret_candidates', 0))} / {int(summary.get('verified_secret_candidates', 0))} |",
        f"| Secret candidates without verification / with multiple scanners | {int(summary.get('secret_candidates_without_verification', 0))} / {int(summary.get('multi_scanner_secret_candidates', 0))} |",
        f"| Secret candidates with assurance gaps / without redaction marker | {int(summary.get('secret_candidates_with_assurance_gaps', 0))} / {int(summary.get('secret_candidates_without_redaction_marker', 0))} |",
        f"| Secret / sensitive-sink route intersections | {int(summary.get('secret_exposure_intersections', 0))} |",
        f"| Exact-path / upstream-route secret intersections | {int(summary.get('exact_path_secret_exposure_intersections', 0))} / {int(summary.get('upstream_route_secret_exposure_intersections', 0))} |",
        f"| Verified / historical secret intersections | {int(summary.get('verified_secret_exposure_intersections', 0))} / {int(summary.get('history_secret_exposure_intersections', 0))} |",
        f"| Unprotected / scanner-confirmed secret intersections | {int(summary.get('unprotected_secret_exposure_intersections', 0))} / {int(summary.get('scanner_confirmed_secret_exposure_intersections', 0))} |",
        f"| Secret intersections with contributing assurance gaps | {int(summary.get('secret_exposure_intersections_with_assurance_gaps', 0))} |",
        f"| Secret intersections with / without candidate tests | {int(summary.get('secret_exposure_intersections_with_candidate_tests', 0))} / {int(summary.get('secret_exposure_intersections_without_candidate_tests', 0))} |",
        f"| Secret intersections with validation / revision gaps | {int(summary.get('secret_exposure_intersections_with_validation_evidence_gaps', 0))} / {int(summary.get('secret_exposure_intersections_with_revision_gaps', 0))} |",
        f"| Secret intersections with failing tests / assurance-prerequisite gaps | {int(summary.get('secret_exposure_intersections_with_failing_tests', 0))} / {int(summary.get('secret_exposure_intersections_with_assurance_prerequisite_gaps', 0))} |",
        f"| Secret intersections without explicit canary validation | {int(summary.get('secret_exposure_intersections_without_canary_validation', 0))} |",
        f"| Secret / sensitive-sink / advisory intersections | {int(summary.get('secret_exposure_advisory_intersections', 0))} |",
        f"| Known-exploited / fix-available compound intersections | {int(summary.get('known_exploited_secret_exposure_advisory_intersections', 0))} / {int(summary.get('fix_available_secret_exposure_advisory_intersections', 0))} |",
        f"| Verified-secret / unprotected compound intersections | {int(summary.get('verified_secret_exposure_advisory_intersections', 0))} / {int(summary.get('unprotected_secret_exposure_advisory_intersections', 0))} |",
        f"| Runtime-observed compound intersections | {int(summary.get('runtime_observed_secret_exposure_advisory_intersections', 0))} |",
        f"| Compound intersections with validation / assurance / temporal gaps | {int(summary.get('secret_exposure_advisory_intersections_with_validation_gaps', 0))} / {int(summary.get('secret_exposure_advisory_intersections_with_assurance_gaps', 0))} / {int(summary.get('secret_exposure_advisory_intersections_with_temporal_gaps', 0))} |",
        f"| Compound intersections without explicit canary validation | {int(summary.get('secret_exposure_advisory_intersections_without_canary_validation', 0))} |",
        f"| Targets analyzed within bound | {int(summary.get('targets_analyzed', 0))} |",
        f"| Python route-applicable / intentionally non-runtime targets | {int(summary.get('route_applicable_targets', 0))} / {int(summary.get('route_not_applicable_targets', 0))} |",
        f"| Targets with a bounded route | {int(summary.get('routed_targets', 0))} |",
        f"| Targets without a bounded route (all dispositions) | {int(summary.get('unrouted_targets', 0))} |",
        f"| Actionable Python route gaps / expected non-runtime dispositions | {int(summary.get('unrouted_route_applicable_targets', 0))} / {int(summary.get('unrouted_expected_non_runtime_targets', 0))} |",
        f"| Python targets absent from graph / without an entry route | {int(summary.get('unrouted_targets_missing_graph_membership', 0))} / {int(summary.get('unrouted_targets_without_entry_route', 0))} |",
        f"| Unrouted target / structural-island intersections | {int(summary.get('unrouted_structural_intersections', 0))} |",
        f"| Unrouted targets in disconnected islands | {int(summary.get('unrouted_targets_in_disconnected_islands', 0))} |",
        f"| Unrouted targets with runtime counter-evidence / dead-code corroboration | {int(summary.get('unrouted_targets_with_runtime_counter_evidence', 0))} / {int(summary.get('unrouted_targets_with_dead_code_corroboration', 0))} |",
        f"| Unrouted targets with candidate entry paths | {int(summary.get('unrouted_targets_with_candidate_entry_paths', 0))} |",
        f"| Unrouted structural intersections with validation gaps | {int(summary.get('unrouted_structural_intersections_with_validation_gaps', 0))} |",
        f"| Runtime-observed routes | {int(summary.get('runtime_observed_routes', 0))} |",
        f"| Routes with line-coverage gaps | {int(summary.get('coverage_gap_routes', 0))} |",
        f"| Routes with validation gaps | {int(summary.get('validation_gap_routes', 0))} |",
        f"| Routes with validation evidence | {int(summary.get('validation_assessed_routes', 0))} |",
        f"| Routes not validation-assessed | {int(summary.get('validation_unassessed_routes', 0))} |",
        f"| Routes with an assigned owner | {int(summary.get('owned_routes', 0))} |",
        f"| Shared route convergence hotspots | {int(summary.get('convergence_hotspots', 0))} |",
        f"| Shared transit/control points | {int(summary.get('shared_control_points', 0))} |",
        f"| Routes benefiting from shared remediation | {int(summary.get('routes_in_convergence_hotspots', 0))} |",
        f"| Owner work queues | {int(summary.get('owner_work_queues', 0))} |",
        f"| Owner queues with exposure / advisory intersections | {int(summary.get('owner_queues_with_exposure_advisory_intersections', 0))} |",
        f"| Shared validation campaigns | {int(summary.get('validation_campaigns', 0))} |",
        f"| Shared validation-test hotspots | {int(summary.get('shared_validation_test_hotspots', 0))} |",
        f"| Campaigns using shared tests | {int(summary.get('campaigns_using_shared_tests', 0))} |",
        f"| Routes using shared tests | {int(summary.get('routes_using_shared_tests', 0))} |",
        f"| Campaigns dependent on one shared test | {int(summary.get('single_test_dependency_campaigns', 0))} |",
        f"| Shared-test evidence strong / qualified / weak / not established | {int(summary.get('shared_test_hotspots_strong', 0))} / {int(summary.get('shared_test_hotspots_qualified', 0))} / {int(summary.get('shared_test_hotspots_weak', 0))} / {int(summary.get('shared_test_hotspots_not_established', 0))} |",
        f"| Shared test files with findings / high-severity findings | {int(summary.get('shared_test_files_with_findings', 0))} / {int(summary.get('shared_test_files_with_high_severity_findings', 0))} |",
        f"| Cross-owner / unowned shared test files | {int(summary.get('cross_owner_shared_test_files', 0))} / {int(summary.get('unowned_shared_test_files', 0))} |",
        f"| Campaigns with selected tests | {int(summary.get('campaigns_with_selected_tests', 0))} |",
        f"| Campaigns with failing tests | {int(summary.get('campaigns_with_failing_tests', 0))} |",
        f"| Campaigns with coverage gaps | {int(summary.get('campaigns_with_coverage_gaps', 0))} |",
        f"| Campaigns at changed control points | {int(summary.get('campaigns_with_changed_controls', 0))} |",
        f"| Campaigns with uncovered changed lines | {int(summary.get('campaigns_with_uncovered_changed_lines', 0))} |",
        f"| Campaigns with runtime-observation gaps | {int(summary.get('campaigns_with_runtime_observation_gaps', 0))} |",
        f"| Campaigns with route tool-assurance prerequisite met | {int(summary.get('campaigns_with_assured_route_evidence', 0))} |",
        f"| Campaigns blocked by route tool assurance | {int(summary.get('campaigns_blocked_by_route_assurance', 0))} |",
        f"| Campaigns with route trust / execution / unassessed gaps | {int(summary.get('campaigns_with_route_trust_gaps', 0))} / {int(summary.get('campaigns_with_route_execution_gaps', 0))} / {int(summary.get('campaigns_with_unassessed_route_evidence', 0))} |",
        f"| Campaigns with single-perspective routes | {int(summary.get('campaigns_with_route_perspective_gaps', 0))} |",
        f"| Campaigns with qualified / weak shared-test evidence | {int(summary.get('campaigns_with_qualified_shared_test_evidence', 0))} / {int(summary.get('campaigns_with_weak_shared_test_evidence', 0))} |",
        f"| Campaigns aligned in current evidence | {int(summary.get('campaigns_aligned_current_evidence', 0))} |",
        f"| Campaigns requiring more evidence | {int(summary.get('campaigns_requiring_evidence', 0))} |",
        f"| Unique campaign test files | {int(summary.get('unique_campaign_test_files', 0))} |",
        f"| Critical / high review campaigns | {int((summary.get('campaigns_by_review_tier') or {}).get('critical', 0))} / {int((summary.get('campaigns_by_review_tier') or {}).get('high', 0))} |",
        f"| Campaign evidence revision-aligned | {int(summary.get('campaigns_revision_aligned', 0))} |",
        f"| Campaign evidence revision-mismatched | {int(summary.get('campaigns_revision_mismatched', 0))} |",
        f"| Campaign evidence digest-matched but binding-unverified | {int(summary.get('campaigns_revision_unverified', 0))} |",
        f"| Campaign evidence revision not established | {int(summary.get('campaigns_revision_unbound', 0))} |",
        f"| Source-bound shared control points | {int(summary.get('campaigns_with_source_bound_control_points', 0))} |",
        f"| Selected-test source bindings | {int(summary.get('selected_test_source_bindings', 0))} |",
        "",
    ]
    return lines
